
package com.itheima.orderService;

import com.itheima.bos.domain.Area;
import com.itheima.bos.domain.Order;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrderService", targetNamespace = "http://service.bos.itheima.com/")
@XmlSeeAlso({

})
public interface OrderService {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "findByCityAndProvinceAndDistrict", targetNamespace = "http://service.bos.itheima.com/", className = "com.itheima.orderService.FindByCityAndProvinceAndDistrict")
    @ResponseWrapper(localName = "findByCityAndProvinceAndDistrictResponse", targetNamespace = "http://service.bos.itheima.com/", className = "com.itheima.orderService.FindByCityAndProvinceAndDistrictResponse")
    public void findByCityAndProvinceAndDistrict(
        @WebParam(name = "arg0", targetNamespace = "")
                Area arg0,
        @WebParam(name = "arg1", targetNamespace = "")
                Order arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "save", targetNamespace = "http://service.bos.itheima.com/", className = "com.itheima.orderService.Save")
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://service.bos.itheima.com/", className = "com.itheima.orderService.SaveResponse")
    public void save(
        @WebParam(name = "arg0", targetNamespace = "")
        Order arg0);

}
